WITH j (iata_id, agency, city, country, region, conteninent) AS (
  VALUES
    ('NYC', 'Metropolitan Transportation Authority (MTA)', 'New York', 'United States East', 'United States', 'North America'),
    ('PHL', 'Southeastern Pennsylvania Transportation Authority (SEPTA)', 'Philadelphia', 'United States East', 'United States', 'North America'),
    ('DCA', 'Washington Metropolitan Area Transit Authority (WMATA)', 'District of Columbia', 'United States East', 'United States', 'North America'),
    ('BOS', 'Massachusetts Bay Transportation Authority (MBTA)', 'Boston', 'United States East', 'United States', 'North America'),
    ('PIT', 'Pittsburgh Regional Transit (PRT)', 'Pittsburgh', 'United States East', 'United States', 'North America'),
    ('LAX', 'Los Angeles County Metropolitan Transportation Authority (Metro)', 'Los Angeles', 'United States West', 'United States', 'North America'),
    ('SFO', 'San Francisco Municipal Transportation Agency (SFMTA)', 'San Francisco', 'United States West', 'United States', 'North America'),
    ('SEA', 'King County Metro (KCM)', 'Seattle', 'United States West', 'United States', 'North America'),
    ('SAC', 'Sacramento Regional Transit District (SacRT)', 'Sacramento', 'United States West', 'United States', 'North America'),
    ('PDX', 'Tri-County Metropolitan Transportation District of Oregon (TriMet)', 'United States West', 'Portland', 'United States', 'North America'),
    ('ATL', 'Metropolitan Atlanta Rapid Transit Authority (MARTA)', 'Atlanta', 'United States South', 'United States', 'North America'),
    ('MIA', 'Miami-Dade Transit', 'Miami', 'United States South', 'United States', 'North America'),
    ('TPA', 'Hillsborough Area Regional Transit (HART)', 'Tampa', 'United States South', 'United States', 'North America'),
    ('SFD', 'Transit Authority of River City (TARC)', 'Louisville', 'United States South', 'United States', 'North America'),
    ('BNA', 'Nashville Metropolitan Transit Authority', 'Nashville', 'United States South', 'United States', 'North America'),
    ('MSP', 'Metro Transit', 'Minneapolis / St. Paul', 'United States Central', 'United States', 'North America'),
    ('STL', 'Metro Transit', 'St. Louis', 'United States Central', 'United States', 'North America'),
    ('MSN', 'Madison Metro Transit', 'Madison', 'United States Central', 'United States', 'North America'),
    ('CMH', 'Central Ohio Transit Authority (COTA)', 'Columbus', 'United States Central', 'United States', 'North America'),
    ('DSM', 'Des Moines Area Regional Transit Authority (DART)', 'United States Central', 'Des Moines', 'United States', 'North America'),
    ('DEN', 'Regional Transportation District (RTD)', 'Denver', 'United States West', 'United States', 'North America'),
    ('PHX', 'Valley Metro', 'Phoenix', 'United States', 'United States West', 'North America'),
    ('SAT', 'VIA Metropolitan Transit', 'San Antonio', 'United States West', 'United States', 'North America'),
    ('BIL', 'Billings Metropolitan Transit (MET)', 'Billings', 'United States West', 'United States', 'North America'),
    ('AUS', 'Capital Metro', 'Austin', 'United States West', 'United States', 'North America'),
    ('YUL', 'Société de transport de Montréal (STM)', 'Montreal', 'Canada East', 'Canada', 'North America'),
    ('YYZ', 'York Region Transit (YRT)', 'York', 'Canada East', 'Canada', 'North America'),
    ('YHM', 'Hamilton Street Railway (HSR)', 'Hamilton', 'Canada East', 'Canada', 'North America'),
    ('YHZ', 'Halifax Transit', 'Halifax', 'Canada East', 'Canada', 'North America'),
    ('YQT', 'Thunder Bay Transit', 'Thunder Bay', 'Canada East', 'Canada', 'North America'),
    ('YVR', 'TransLink', 'Vancouver', 'Canada West', 'Canada', 'North America'),
    ('YYC', 'Calgary Transit', 'Calgary', 'Canada West', 'Canada', 'North America'),
    ('YEG', 'Edmonton Transit System (ETS)', 'Edmonton', 'Canada West', 'Canada', 'North America'),
    ('YXE', 'Saskatoon Transit', 'Saskatoon', 'Canada West', 'Canada', 'North America'),
    ('YYJ', 'BC Transit', 'Victoria', 'Canada West', 'Canada', 'North America'),
    ('NLD', 'OVAPI', 'Greater', 'Netherlands', 'Europe West', 'Europe'),
    ('ARN', 'Storstockholms Lokaltrafik (SL)', 'Stockholm', 'Europe West', 'Europe'),
    ('HEL', 'Helsinki Regional Transport Authority (HSL)', 'Helsinki', 'Europe'),
    ('DUB', 'National Transport Authority', 'Dublin', 'Ireland', 'Europe West', 'Europe'),
    ('FCO', 'Tramway and Bus Agency of the City of Rome (ATAC), TPL', 'Italy', 'Europe West', 'Europe'),
    ('WAW', 'Zarząd Transportu Miejskiego (ZTM)', 'Warsaw', 'Poland', 'Europe Central', 'Europe'),
    ('KRK', 'Zarząd Transportu Publicznego (ZTP)', 'Kraków', 'Poland', 'Europe Central', 'Europe'),
    ('PRG', 'Prague Integrated Transport (PID)', 'Prague', 'Czech Republic', 'Europe Central', 'Europe'),
    ('GDN', 'Gdańsk Municipal Transport (ZKM)', 'Gdańsk', 'Poland', 'Europe'),
    ('SYD', 'Transport for NSW', 'Sydney', 'Oceania', 'Australia', 'Oceania'),
    ('BNE', 'TransLink', 'Brisbane', 'Oceania', 'Australia', 'Oceania'),
    ('ADL', 'Adelaide Metro', 'Adelaide', 'Australia', 'Oceania', 'Oceania'),
    ('AKL', 'Auckland Transport (AT)', 'Auckland', 'New Zealand', 'Oceania', 'Oceania'),
    ('CHC', 'Environment Canterbury', 'Christchurch', 'New Zealand', 'Oceania', 'Oceania'),
    ('DEL', 'Delhi Transport Corporation (DTC)', 'Delhi', 'India', 'Asia', 'Asia')
)
INSERT INTO agency (iata_id, agency, city, country)
SELECT i.iata_id, i.agency, i.city, i.country
FROM j i
LEFT JOIN agency k ON k.iata_id = i.iata_id
WHERE k.iata_id IS NULL;