WITH j (iata_id, agency, city, country) AS (
  VALUES
    ('NYC', 'Metropolitan Transportation Authority (MTA)', 'New York', 'United States'),
    ('PHL', 'Southeastern Pennsylvania Transportation Authority (SEPTA)', 'Philadelphia', 'United States'),
    ('DCA', 'Washington Metropolitan Area Transit Authority (WMATA)', 'District of Columbia', 'United States'),
    ('BOS', 'Massachusetts Bay Transportation Authority (MBTA)', 'Boston', 'United States'),
    ('PIT', 'Pittsburgh Regional Transit', 'Pittsburgh', 'United States'),
    ('BAL', 'Maryland Transit Administration (MTA)', 'Baltimore', 'United States'),
    ('LAX', 'Los Angeles County Metropolitan Transportation Authority (Metro)', 'Los Angeles', 'United States'),
    ('SFO', 'San Francisco Municipal Transportation Agency (SFMTA)', 'San Francisco', 'United States'),
    ('SAN', 'San Diego Metropolitan Transit System (MTS)', 'San Diego', 'United States'),
    ('SEA', 'King County Metro (KCM)', 'Seattle', 'United States'),
    ('SAC', 'Sacramento Regional Transit District (SacRT)', 'Sacramento', 'United States'),
    ('PDX', 'Tri-County Metropolitan Transportation District of Oregon (TriMet)', 'Portland', 'United States'),
    ('ATL', 'Metropolitan Atlanta Rapid Transit Authority (MARTA)', 'Atlanta', 'United States'),
    ('AUS', 'Capital Metro', 'Austin', 'United States'),
    ('MIA', 'Miami-Dade Transit', 'Miami', 'United States'),
    ('TPA', 'Hillsborough Area Regional Transit (HART)', 'Tampa', 'United States'),
    ('LOU', 'Transit Authority of River City (TARC)', 'Louisville', 'United States'),
    ('BNA', 'Nashville Metropolitan Transit Authority', 'Nashville', 'United States'),
    ('MSP', 'Metro Transit', 'Twin Cities', 'United States'),
    ('STL', 'Metro Transit', 'St Louis', 'United States'),
    ('MSN', 'Madison Metro Transit', 'Madison', 'United States'),
    ('CMH', 'Central Ohio Transit Authority (COTA)', 'Columbus', 'United States'),
    ('LAN', 'Capital Area Transportation Authority (CATA)', 'Lansing', 'United States'),
    ('DSM', 'Des Moines Area Regional Transit Authority (DART)', 'Des Moines', 'United States'),
    ('DEN', 'Regional Transportation District (RTD)', 'Denver', 'United States'),
    ('PHX', 'Valley Metro', 'Phoenix', 'United States'),
    ('SAT', 'VIA Metropolitan Transit', 'San Antonio', 'United States'),
    ('YUL', 'Exo', 'Montreal', 'Canada'),
    ('YYZ', 'York Region Transit (YRT)', 'York', 'Canada'),
    ('YHM', 'Hamilton Street Railway (HSR)', 'Hamilton', 'Canada'),
    ('YHZ', 'Halifax Transit', 'Halifax', 'Canada'),
    ('YQT', 'Thunder Bay Transit', 'Thunder Bay', 'Canada'),
    ('YVR', 'TransLink', 'Vancouver', 'Canada'),
    ('YYC', 'Calgary Transit', 'Calgary', 'Canada'),
    ('YEG', 'Edmonton Transit System (ETS)', 'Edmonton', 'Canada'),
    ('YXE', 'Saskatoon Transit', 'Saskatoon', 'Canada'),
    ('YYJ', 'BC Transit', 'Victoria', 'Canada'),
    ('AMS', 'OVAPI', 'Netherlands', 'Europe'),
    ('STO', 'Storstockholms Lokaltrafik (SL)', 'Stockholm', 'Europe'),
    ('HEL', 'Helsinki Regional Transport Authority (HSL)', 'Helsinki', 'Europe'),
    ('DUB', 'National Transport Authority', 'Dublin', 'Europe'),
    ('FCO', 'Tramway and Bus Agency of the City of Rome (ATAC), TPL', 'Italy', 'Europe'),
    ('WAW', 'Zarząd Transportu Miejskiego (ZTM)', 'Warsaw', 'Poland'),
    ('KRK', 'Zarząd Transportu Publicznego (ZTP)', 'Kraków', 'Poland'),
    ('PRG', 'Golemio', 'Prague', 'Europe'),
    ('GDN', 'Gdańsk Municipal Transport (ZKM)', 'Gdańsk', 'Europe'),
    ('ZAG', 'Zagreb Electric Tram (ZET)', 'Zagreb', 'Europe'),
    ('SYD', 'Transport for NSW', 'Sydney', 'Oceania'),
    ('MEL', 'Public Transport Victoria (PTV)', 'Melbourne', 'Oceania'),
    ('BNE', 'TransLink', 'Brisbane', 'Oceania'),
    ('ADL', 'Adelaide Metro', 'Adelaide', 'Oceania'),
    ('AKL', 'Auckland Transport (AT)', 'Auckland', 'Oceania'),
    ('CHC', 'Environment Canterbury', 'Christchurch', 'Oceania'),
    ('TPE', 'Taipei City Government', 'Taipei', 'Asia'),
    ('DEL', 'Delhi Transport Corporation (DTC)', 'Delhi', 'Asia')
)
INSERT INTO agency (iata_id, agency, city, country)
SELECT i.iata_id, i.agency, i.city, i.country
FROM j i
LEFT JOIN agency k ON k.iata_id = i.iata_id
WHERE k.iata_id IS NULL;